name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, pdo_sqlite
        tools: composer:v2

    - name: Copy .env file
      run: cp .env.example .env

    - name: Setup Application
      run: make setup

    - name: Run Code Style Check
      run: make lint

    - name: Run Static Analysis
      run: make phpstan

    - name: Run Tests
      run: make test 